### ISSUE TITLE
Module broken in Python 3

### ISSUE THREAD

**Issue by gtie** [Bassintag/spark-python-sdk#1]
Current imports do not work (when module is pip-installed):

```
$ python                                                                                                                                                                    [203/335]
Python 3.5.3 (default, Sep 14 2017, 22:58:41)                                                  
[GCC 6.3.0 20170406] on linux                                                              
Type "help", "copyright", "credits" or "license" for more information.                     
>>> import sparkpy                                                                                                                     
Traceback (most recent call last):                                                                                                 
  File "<stdin>", line 1, in <module>                                                                                            
  File "/home/XXXX/.virtualenvs/test3/lib/python3.5/site-packages/sparkpy/__init__.py", line 6, in <module>          
    from License import License                                                                                  
ImportError: No module named 'License'                                                                       
```
See https://www.python.org/dev/peps/pep-0404/#imports for an explanation. 

Solution is to put a "." in front of imports to turn them into explicit relative ones.

**Comment by gtie** [comment]
A quick-and-dirty live edit can get you rid of those after an actual installation:
```
sed -i -r 's/^from ([A-Z])/from .\1/g' your/path/to/site-packages/sparkpy/*.py
sed -i -r 's/^import ([A-Z])/from . import \1/g' your/path/to/site-packages/sparkpy/*.py
```
